initial commit
Denisprkh/epam-lab-esm pull request #1
Opened 2020-10-22 10:59 UTC by Denisprkh

2020-10-22 18:04 UTC, NatalliaKhadunai commented
I'm not able to run gradle tasks from the project root.

P.s. I googled possible reasons for the issues and it looks like the reason is missing file `/epam-lab-esm/gradle/wrapper/gradle-wrapper.jar`.

**Note: please always double-check that your code can be built and deployed before submitting a PR!**

2020-10-22 18:34 UTC, NatalliaKhadunai commented
Please provide sql file for database initialization.

2020-10-22 20:01 UTC, Denisprkh commented
> I'm not able to run gradlew tasks from the project root. Please fix this.
> 
> P.s. I googled possible reasons for the issues and it looks like the reason is missing file `/epam-lab-esm/gradle/wrapper/gradle-wrapper.jar`.
> 
> **Note: please always double-check that your code can be built and deployed before submitting a PR!**

graddle-wrapper.jar is added

2020-10-22 20:02 UTC, Denisprkh commented
> Please provide sql file for database initialization.

db creation script is added

2020-10-23 04:46 UTC, NatalliaKhadunai commented
Please pay attention to formatting. At the moment there are a lot of missing spaces before curly braces, comas, etc.

2020-10-23 13:15 UTC, NatalliaKhadunai requested changes

2020-10-25 07:13 UTC, NatalliaKhadunai commented on dbinfo/esm.sql
> +    ON UPDATE NO ACTION,
`NO ACTION` is a default option for `ON DELETE` and `ON UPDATE` so we can remove these lines everywhere.

2020-10-25 07:13 UTC, NatalliaKhadunai commented on src/main/resources/database.properties
> +  UTF-8&useSSL=TRUE&allowPublicKeyRetrieval=TRUE
I think we can remove all the properties from url. I read the documentation and didn't find any proof that we need them and the application works fine without them.

2020-10-25 07:13 UTC, NatalliaKhadunai commented on src/main/java/com/epam/esm/repository/tag/TagSqlQuery.java
> +    public static final String FIND_TAG_BY_ID = "SELECT tag_id, name FROM tag WHERE tag_id = ?";
Maybe `SELECT *` ?

2020-10-25 07:13 UTC, NatalliaKhadunai commented on src/main/java/com/epam/esm/config/AppConfig.java
> +        dataSource.setDriverClass(com.mysql.cj.jdbc.Driver.class);
This is still implemented slightly incorrect. Here is how we should use `@Value`:
![image](https://user-images.githubusercontent.com/17936204/97101006-a4cbc080-16aa-11eb-9de5-60855f3f2375.png)

2020-10-25 07:18 UTC, NatalliaKhadunai commented on src/main/java/com/epam/esm/config/SpringMvcDispatcherServletInitializer.java
> +public class SpringMvcDispatcherServletInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {
It looks like we can remove the class. App runs fine without it.

2020-10-25 14:00 UTC, Denisprkh commented
Code is ready for the next review, @NatalliaKhadunai

2020-10-25 17:06 UTC, merged